### ISSUE TITLE
throwing errors when cant find custom type declaration

### ISSUE THREAD

**Issue by uladkasach** [uladkasach/sql-code-generator#7]
``` npx sql-code-generator generate
TSError: ⨯ Unable to compile TypeScript:
src/utils/config.ts:2:20 - error TS7016: Could not find a declaration file for module 'config-with-paramstore'. '/var/www/git/Tugether/svc-idea-curation/node_modules/config-with-paramstore/dist/config.js' implicitly has an 'any' type.
  Try `npm install @types/config-with-paramstore` if it exists or add a new declaration (.d.ts) file containing `declare module 'config-with-paramstore';`
2 import Config from 'config-with-paramstore';
                     ~~~~~~~~~~~~~~~~~~~~~~~~
    at createTSError (/var/www/git/Tugether/svc-idea-curation/node_modules/sql-code-generator/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/var/www/git/Tugether/svc-idea-curation/node_modules/sql-code-generator/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/var/www/git/Tugether/svc-idea-curation/node_modules/sql-code-generator/node_modules/ts-node/src/index.ts:530:36)
    at Object.compile (/var/www/git/Tugether/svc-idea-curation/node_modules/sql-code-generator/node_modules/ts-node/src/index.ts:735:32)
    at Module.m._compile (/var/www/git/Tugether/svc-idea-curation/node_modules/sql-code-generator/node_modules/ts-node/src/index.ts:814:43)
    at Object.require.extensions.<computed> [as .ts] (/var/www/git/Tugether/svc-idea-curation/node_modules/sql-code-generator/node_modules/ts-node/src/index.ts:817:12)```

is this a ts-node issue?

**Comment by uladkasach** [comment]
relevant? https://github.com/TypeStrong/ts-node/issues/391#issuecomment-349192156

**Comment by uladkasach** [comment]
perhaps

**Comment by uladkasach** [comment]
perhaps to eliminate the cyclical dependency and being blocked by all other type definition errors that could arise in the process (e.g., the source sql was a little off and so now the generated types.ts file will not compile) we should simply grab the sql string out of the file with regex?

should be pretty safe if we expect it to start w/ a named export and be in a string template literal e.g.: 
```ts
export const query = `__SQL__
__SQL_CONT__
`
```

and get the full sql

**Comment by uladkasach** [comment]
completed here: https://github.com/uladkasach/sql-code-generator/commit/00656df060ef83b5b59f05583cc29fc5a01ec14d
